services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: documind_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: documind
    ports:
      - "5432:5432"
    volumes:
      - documind_pgdata:/var/lib/postgresql/data

volumes:
  documind_pgdata: